# Generated by Django 4.2.5 on 2024-01-21 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeinout',
            name='time_start',
            field=models.CharField(blank=True, default='05:17 PM', max_length=50, null=True),
        ),
    ]
