# Generated by Django 4.2.5 on 2024-01-21 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_timeinout_time_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeinout',
            name='time_start',
            field=models.TimeField(default='05:20 PM', null=True),
        ),
    ]
