# Generated by Django 4.2.5 on 2024-01-21 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_timeinout_time_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedreport',
            name='total_time',
        ),
        migrations.AlterField(
            model_name='generatedreport',
            name='time_start',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='timeinout',
            name='time_start',
            field=models.CharField(blank=True, default='11:08 PM', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='timeinout',
            name='total_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
